name: Run C Code and Update README

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install GCC
      run: sudo apt update && sudo apt install -y build-essential

    - name: Compile C code
      run: gcc main.c -o main

    - name: Run C binary and save output
      run: ./main > result.txt

    - name: Insert result into README.md using sed
      run: |
        RESULT=$(cat result.txt)
        sed -i "/<!-- RESULT_START -->/,/<!-- RESULT_END -->/c\\
        <!-- RESULT_START -->\\
        \`\`\`\\
        $RESULT\\
        \`\`\`\\
        <!-- RESULT_END -->" README.md

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add README.md result.txt
        git commit -m "Update README and add result.txt" || echo "No changes to commit"
        git push
